/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewa.mobil.View.Penyewaan;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import org.jdatepicker.DateModel;
import sewa.mobil.Controller.SewaController;
import sewa.mobil.Model.Object.Mobil;

import sewa.mobil.Model.Object.Pelanggan;
import sewa.mobil.Model.Object.Supir;
import sewa.mobil.View.Mobil.BrowseMobilView;
import sewa.mobil.View.Pelanggan.BrowsePelangganView;
import sewa.mobil.View.Supir.BrowseSupirView;

/**
 *
 * @author omandotkom
 */
public class SewaView extends javax.swing.JFrame {

    /**
     * Creates new form SewaView
     */
    public SewaView() {
        initComponents();
        /*  UtilDateModel model = new UtilDateModel();
JDatePanel datePanel = new JDatePanel(model);
JDatePicker datePicker = new JDatePicker();

this.add(datePicker);
datePicker.showPopup();
         */ }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        lblIDPelanggan = new javax.swing.JLabel();
        btnBrowsePelanggan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNamaMobil = new javax.swing.JTextField();
        lblIDMobil = new javax.swing.JLabel();
        btnBrowseMobil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNamaSupir = new javax.swing.JTextField();
        lblSupir = new javax.swing.JLabel();
        btnBrowseSupir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateSewa = new org.jdatepicker.JDatePicker();
        dateKembali = new org.jdatepicker.JDatePicker();
        jLabel6 = new javax.swing.JLabel();
        cmbSupir = new javax.swing.JCheckBox();
        lblHari = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblBiaya = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pelanggan : ");

        txtNamaPelanggan.setText("jTextField1");

        lblIDPelanggan.setText("jLabel2");

        btnBrowsePelanggan.setText("Pilih");
        btnBrowsePelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePelangganActionPerformed(evt);
            }
        });

        jLabel2.setText("Mobil");

        txtNamaMobil.setText("jTextField1");

        lblIDMobil.setText("jLabel2");

        btnBrowseMobil.setText("Pilih");
        btnBrowseMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseMobilActionPerformed(evt);
            }
        });

        jLabel3.setText("Supir");

        txtNamaSupir.setText("jTextField1");
        txtNamaSupir.setEnabled(false);

        lblSupir.setText("Tidak Ditentukan");

        btnBrowseSupir.setText("Pilih");
        btnBrowseSupir.setEnabled(false);
        btnBrowseSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseSupirActionPerformed(evt);
            }
        });

        jLabel4.setText("Sewa");

        jLabel5.setText("Kembali");

        dateSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSewaActionPerformed(evt);
            }
        });

        dateKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateKembaliActionPerformed(evt);
            }
        });

        jLabel6.setText("Jumlah Hari");

        cmbSupir.setText("Supir");
        cmbSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupirActionPerformed(evt);
            }
        });

        lblHari.setText("lblhari");

        txtHarga.setText("jTextField1");

        jLabel7.setText("Total Biaya : ");

        lblBiaya.setText("jLabel8");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel8.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIDPelanggan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBrowsePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSupir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNamaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBrowseSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbSupir))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblIDMobil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNamaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBrowseMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHari)
                                    .addComponent(lblBiaya)))))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(btnHitung)
                    .addComponent(btnSimpan))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDPelanggan)
                    .addComponent(btnBrowsePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDMobil)
                    .addComponent(btnBrowseMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupir)
                    .addComponent(btnBrowseSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblHari))
                .addGap(32, 32, 32)
                .addComponent(btnHitung)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblBiaya)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String parseDateToString(DateModel model){
        tglSewaDate = new Date();
        tglSewaDate.setYear(dateSewa.getModel().getYear());
        tglSewaDate.setDate(dateSewa.getModel().getDay());
        tglSewaDate.setMonth(dateSewa.getModel().getMonth());
        
     String d, m;
        
        if (model.getMonth() < 10) {
            m = "0" + model.getMonth();
        } else {
            m = String.valueOf(model.getMonth());
        }
        if (model.getDay() < 10) {
            d = "0" + model.getDay();
        } else {
            d = String.valueOf(model.getDay());
        }
tglSewa = dateSewa.getModel().getYear() + "-" + m + "-" + d;
        return tglSewa;
    }
    private void dateSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSewaActionPerformed
        // TODO add your handling code here
       
        System.out.println(parseDateToString(dateSewa.getModel()));

    }//GEN-LAST:event_dateSewaActionPerformed
    String tglSewa, tglKembali;

    private Date tglKembaliDate,tglSewaDate; 
    private void dateKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateKembaliActionPerformed
        // TODO add your handling code here:

        tglKembaliDate = new Date();
        tglKembaliDate.setYear(dateKembali.getModel().getYear());
        tglKembaliDate.setDate(dateKembali.getModel().getDay());
        tglKembaliDate.setMonth(dateKembali.getModel().getMonth());
        
        LocalDateTime sewaDateTime = tglSewaDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();

        LocalDateTime kembaliDateTime = tglKembaliDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();

        Duration duration = Duration.between(kembaliDateTime, sewaDateTime);
        long diff = Math.abs(duration.toDays());
        lblHari.setText(String.valueOf(diff));
    }//GEN-LAST:event_dateKembaliActionPerformed

    private void btnBrowsePelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePelangganActionPerformed
        final JDialog frame = new JDialog(this, "Open", true);
        BrowsePelangganView vie = new BrowsePelangganView();
        frame.getContentPane().add(vie);
        frame.pack();
        frame.setVisible(true);
        Pelanggan pelanggan = vie.getPelanggan();
        txtNamaPelanggan.setText(pelanggan.getNama());
        lblIDPelanggan.setText(String.valueOf(pelanggan.getId()));
        // TODO add your handling code here:
        /*    PelangganView aWindow = new PelangganView();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        aWindow.setBounds(center.x - aWindow.getWidth() / 2, center.y - aWindow.getHeight() / 2, aWindow.getWidth(),
                aWindow.getHeight());
        aWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        aWindow.show();
        // Display the window
 
        Pelanggan pelanggan = aWindow.getPelanggan();
    //    pelangganView.setVisible(false);
      //  pelangganView.dispose();
      System.out.println("namanya " + pelanggan.getNama());
        txtNamaPelanggan.setText(pelanggan.getNama());
        lblIDPelanggan.setText(String.valueOf(pelanggan.getId()));*/
    }//GEN-LAST:event_btnBrowsePelangganActionPerformed

    private void btnBrowseMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseMobilActionPerformed
        final JDialog frame = new JDialog(this, "Open", true);
        BrowseMobilView vie = new BrowseMobilView();
        frame.getContentPane().add(vie);
        frame.pack();
        frame.setVisible(true);
        Mobil mobil = vie.getMobil();
        txtNamaMobil.setText(mobil.getNamaMobil());
        lblIDMobil.setText(String.valueOf(mobil.getId()));
        txtHarga.setText(String.valueOf(mobil.getHargaSewa()));
    }//GEN-LAST:event_btnBrowseMobilActionPerformed

    private void cmbSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupirActionPerformed
        // TODO add your handling code here:
        if (cmbSupir.isSelected()) {
            txtNamaSupir.setText("");
            txtNamaSupir.setEnabled(true);
            lblSupir.setEnabled(true);
            btnBrowseSupir.setEnabled(true);
       
        } else {
            lblSupir.setText("Tidak Ditentukan");
            txtNamaSupir.setText("");
            txtNamaSupir.setEnabled(false);
            lblSupir.setEnabled(false);
            btnBrowseSupir.setEnabled(false);
        }
    }//GEN-LAST:event_cmbSupirActionPerformed

    private void btnBrowseSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseSupirActionPerformed
        // TODO add your handling code here:
        final JDialog frame = new JDialog(this, "Open", true);
        BrowseSupirView vie = new BrowseSupirView();
        frame.getContentPane().add(vie);
        frame.pack();
        frame.setVisible(true);
        Supir supir = vie.getSupir();
        lblSupir.setText(supir.getNik());
        txtNamaSupir.setText(supir.getNama());
    }//GEN-LAST:event_btnBrowseSupirActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            // TODO add yoaur handling code here:
            SewaController sewaController = new SewaController(0, Integer.valueOf(lblIDPelanggan.getText()),
                    Integer.valueOf(lblIDMobil.getText()), lblSupir.getText(), tglSewa, tglKembali,
                    Double.valueOf(txtHarga.getText()), "disewa", Integer.valueOf(lblHari.getText()));
          
            lblBiaya.setText(String.valueOf(sewaController.totalBiaya()));

        } catch (Exception ex) {
            Logger.getLogger(SewaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
   
        
  SewaController sewaController = new SewaController(0,Integer.valueOf(lblIDPelanggan.getText()),
            Integer.valueOf(lblIDMobil.getText()), lblSupir.getText(),parseDateToString(dateSewa.getModel()),parseDateToString(dateKembali.getModel()),
            Double.valueOf(txtHarga.getText()),"disewa",Integer.valueOf(lblHari.getText()), Double.valueOf(lblBiaya.getText()));
         
            
    sewaController.saveData();

 /*Sewa sewa = new SewaModel().getLastRecord();
System.out.println("TOTAL BIAYA " + sewa.getTotalBiaya() );
                ReportView report = new ReportView(sewa);
                report.build();
*/
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseMobil;
    private javax.swing.JButton btnBrowsePelanggan;
    private javax.swing.JButton btnBrowseSupir;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox cmbSupir;
    private org.jdatepicker.JDatePicker dateKembali;
    private org.jdatepicker.JDatePicker dateSewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblIDMobil;
    private javax.swing.JLabel lblIDPelanggan;
    private javax.swing.JLabel lblSupir;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaMobil;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNamaSupir;
    // End of variables declaration//GEN-END:variables
}
